version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: sh -c "$(curl -ssL https://taskfile.dev/install.sh)" -- -d -b /usr/bin
      - run: task cli-cover-report
  release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: sh -c "$(curl -ssL https://taskfile.dev/install.sh)" -- -d -b /usr/bin
      - run: task tools download-reveal
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
              tags:
                only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
